#version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - '8810:80'
        volumes:
            - ./:/var/www/
            - ./Docker/nginx/conf.d/:/etc/nginx/conf.d/
        container_name: server_app_docker

    app:
        build:
            context: .
            dockerfile: Docker/php/DockerFile
        volumes:
            - ./:/var/www
            - ./storage/app/public:/var/www/html/public/storage
        container_name: laravel_docker_app
        depends_on:
            - db

    db:
        image: mysql:8.0
        restart: no
        volumes:
            - ./tmp/db:/var/lib/mysql
            - ./Docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
        environment:
            MYSQL_DATABASE: bddockerlar
            MYSQL_ROOT_PASSWORD: 3003
        ports:
            - '8763:3306'
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: docker_proj_db

